{% set name = "flask-pymongo" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Flask-PyMongo-{{ version }}.tar.gz
  sha256: 620eb02dc8808a5fcb90f26cab6cba9d6bf497b15032ae3ca99df80366e33314

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - vcversioner
  run:
    - flask >=0.11
    - pymongo >=3.3
    - python >={{ python_min }}

test:
  imports:
    - flask_pymongo
    - flask_pymongo.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://flask-pymongo.readthedocs.org/
  summary: PyMongo support for Flask applications
  license: BSD-3-Clause
  license_file: docs/_themes/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
